apiVersion: 1

contactPoints:
  - orgId: 1
    name: BADA-SNS
    receivers:
      - uid: bada-sns-receiver
        type: sns
        settings:
          topic: ${sns_topic_arn}
          authProvider: default
          subject: "[BADA Alert] {{ .CommonLabels.alertname }}"
          messageFormat: body
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: BADA-SNS
    group_by:
      - grafana_folder
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
